name: CI
# запускается когда pull_request или push в ветку develop
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # копируем все папаки
      - uses: actions/checkout@v2
      - name: Cache node_modules folder
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: use NodeJS
      # устанавливаем 12 ноду
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      # тоже что и npm install
      - run: npm ci
      # запускаем скрипт prittifaer из файла package.json
      - run: npm run format:check
      # запускаем test из файла package.json
      - run: npm run test -- --coverage
        env:
          CI: true
      # ляет копировать код проекта и делать ссылку на zip файл в пазделе артифакты в actions в самой джабсе
      - name: Upload artifact Test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: Build Project
      # если событие является push
        if: github.event_name == 'push'
        # запускаем predeploy из файла package.json
        run: npm run predeploy
      - name: Upload artifact Build Folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: Check folders
        run: |
          ls -la
          pwd
      - name: Deploy Project to Develop site
      # опять если событие является push
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
          # запускаем action который скопирует папаку build в хостинг github pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
       # https://github.com/semantic-release/semantic-release
       # если пушить изменения в master можно указать версию релиза, для этого через npm устанавливаем плагин semantic-release
       # он автоматически генерируе версию в зависимости от коммита который ты пушишь.
       # обязательно создаем файл release.config в корне, в нем указываем все данные и плагины для работы с мастером
       # github.event_name == 'push' && github.ref == 'refs/heads/master условие сработает только когда пуш в мастер
       # git commit -m "perf: some description" - performance обновит мажорную версию (ломают предыдущую функциональность)
       # git commit -m "feat: some description" обновит минорную версию (новые фичи, не ломают)
       # git commit -m "fix: some description" обновит патч версию (исправление багов)
       # git commit -m "docs: some description" обновит патч версию (исправление багов, новая документация)
       # git commit -m "ci: some description" обновит патч версию (изменения в ymlфайле)
       # git commit -m "style: some description" обновит патч версию (обновление стилистики проекта)
      - name: Create a Release Version
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
      - name: Build Project
      # опять если событие является push
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
          # запускаем action который деплоит на продакшн
        run: npm run build
      - name: Deploy Project to Production site
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'   
        run: npx surge --project ./build --domain  yudbox-reactapp.surge.sh
        # чтоб сгенерировать токен пишем surge SURGE_TOKEN
        # чтоб узнать свой логин пишем surge whoami
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}