name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # тоже что и npm install
      - run: npm ci
      - run: npm run format:check
      - run: npm run test -- --coverage
        env:
          CI: true
      - name: Check folders
        run: |
          ls -la
          pwd
      - name: Build Project
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
