on: push
jobs:
  test-custom-action:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/hello
      id: hello
      with:
       who-say-hello: "Alex"
    - run: |
        echo "Time: ${{ steps.hello.outputs.my-time }}"  
        echo ${CASTOM_VAR}