on: push
jobs:
  test-custom-action:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/issue
      id: issue
      with:
        token: ${{ secrets.CUSTOM_TOKEN }}
        title: mytitle
        body: mybody
        assignees: |
          yudbox
          ydbox2
    - run: |
        echo ${{ steps.issue.outputs.issue }}
    - uses: ./.github/actions/hello
      id: hello
      with:
       who-say-hello: "Alex"
    - run: |
        echo "Time: ${{ steps.hello.outputs.my-time }}"  
        echo ${CASTOM_VAR}